debug:
  true

server:
  port: 8080

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rancho?serverTimezone=UTC
    username: root
    password: 123456
  #redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
#  cache:
#    redis:
#      time-to-live: 10000
#      use-key-prefix: false

#下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
